### ISSUE TITLE
Test functionality is missing

### ISSUE THREAD

**Issue by belidzs** [paylike/api-docs#13]
I'd like to implement test scenarios where a recurring payment (when I create a new transaction based on a previous, successful payment without the customer being present) fails, but to me it seems like like this particular API doesn't offer this capability. Am I correct? If yes, could you please implement it? I see no other way testing these scenarios.

The "other" API [seems to offer this functionality already](https://github.com/paylike/api-reference/blob/main/payments/index.md), but I think there are currently no libraries implementing it.

**Comment by tjconcept** [comment]
Hi @belidzs 

That's correct. This API is generally frozen and won't be expanded with regards to payments. That development will happen on the newer payments API you linked. Thus, to test such scenarios against our APIs, you will have to wait for the new payments API to acquire the functionality to create "subsequent" payments.

I am only aware of our official libraries (linked from the readme of the new API) implementing it currently.
